version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  test-node8:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:ci
  test-node9:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:ci
  test-node10:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:ci
  test-node11:
    docker:
      - image: circleci/node:11
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:ci
  test-node12:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:ci
  test-node13:
    docker:
      - image: circleci/node:13
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:ci
  publish-beta:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to beta channel
          command: npm publish --tag beta
  publish-stable:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to stable channel
          command: npm publish --tag latest

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test-node8:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-node9:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-node10:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-node11:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-node12:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-node13:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish-beta:
          requires:
            - test-node8
            - test-node9
            - test-node10
            - test-node11
            - test-node12
            - test-node13
          filters:
            tags:
              only: /^v\d*\.\d*\.\d*-beta\.\d*$/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - test-node8
            - test-node9
            - test-node10
            - test-node11
            - test-node12
            - test-node13
          filters:
            tags:
              only: /^v\d*\.\d*\.\d*$/
            branches:
              ignore: /.*/
      - publish-stable:
          requires:
            - hold
          filters:
            tags:
              only: /^v\d*\.\d*\.\d*$/
            branches:
              ignore: /.*/
